# Database connection
flyway.url=jdbc:mysql://18.237.88.242:3306/devopsdb
flyway.user=root
flyway.password=root

# SQL file location (inside container)
flyway.locations=filesystem:/flyway/sql

# Safety + validation
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.cleanDisabled=true

# Schema history
flyway.table=flyway_schema_history
